services:
  pi-dashboard:
    build: 
      context: .
      target: dev # We gebruiken de dev stage voor live-reload
    container_name: pi-dashboard
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - .:/app # De "magic": je lokale code wordt in de container gespiegeld
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - dashboard-net

networks:
  dashboard-net:
    driver: bridge
