services:
  controller:
    build:
      context: .
    container_name: streamdeck-daemon
    privileged: true
    restart: unless-stopped
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./app:/app
    environment:
      - DASHBOARD_WS_URL=ws://localhost:8080/ws
